# Generated by Django 3.2.16 on 2023-02-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparision_cepe_all_oi_high',
            name='underlyingValue_diff',
            field=models.FloatField(max_length=25, null=True),
        ),
    ]
