# Generated by Django 3.2.16 on 2023-03-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comparision_cepe_all_oi_high_underlyingvalue_diff'),
    ]

    operations = [
        migrations.CreateModel(
            name='selecttime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_date', models.DateField(null=True)),
            ],
        ),
    ]
